### ISSUE TITLE
Not running, WARN: Unresolved specs during Gem::Specification.reset: and E0817

### ISSUE THREAD

**Issue by hahwul** [rapid7/metasploit-aggregator#10]
Hi rapid7 team.
I have problem of starting metasploit-aggregator. how do you solv it?

If run metasploit-aggregator command, an error occurs, but it run.
```
#> metasploit-aggregator -h
WARN: Unresolved specs during Gem::Specification.reset:
      grpc (>= 0)
      rex-arch (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
2017-08-17 07:05:25 +0900 Starting administration service on 127.0.0.1:2447
```

open 2447 port
```
#>netstat -an | grep 2447
tcp6       0      0 127.0.0.1:2447          :::*                    LISTEN     
```

But, an error occurs when you execute the "aggregator_connect" command on metasploit.
Of course, the aggregator plugin was loaded.
```
HAHWUL > aggregator_connect 127.0.0.1:2447
[*] Connecting to Aggregator instance at 127.0.0.1:2447...
E0817 06:40:03.591233870   25993 uri_parser.c:60]            bad uri.scheme: ''
E0817 06:40:03.591334832   25993 uri_parser.c:66]                             ^ here
E0817 06:40:03.591373079   25993 http_proxy.c:56]            cannot parse value of 'http_proxy' env var

```
Thank you.

**Comment by jmartin-r7** [comment]
Sorry it is unclear how you installed metasploit-aggragator, is this from:
* the metasploit-framework omnibus installer (deb, msi, pkg)
* as part of a Kali Linux installation
* a separate direct repository clone
* direct gem installation or bundler require?

Also please provide any env details that you can.  What OS installation, how the ruby execution environment was installed, etc.

`lsof -i -n -P` may also provide some additional details about how the ports are being held.

Based on the warning message you may have executed this from a metasploit-framework development installation that has some older gems installed `bundle clean --force` would remove these from the gemset and resolve the warning however should be used with caution if you installed the current bundle in the system gemset.

A quick guess based on the error seen suggests that you may have an incompatible gem in your gemset or possibly multiple versions of grpc, and `msfconsole` may be selecting a package incompatible with the one metasploit-aggregator is selecting.  In which case the `bundle install && bundle clean --force` may resolve the issue.

**Comment by hahwul** [comment]
Thank you for Answer.

First. I solved the error with "gem update command". however another problem occurred.

After gem update, the following error occurs.
Plugin will not load after gem update.
(There is a "aggregator.rb" file in metasploit plugins directory)

```
HAHWUL > load aggregator
[-] Failed to load plugin from /usr/share/metasploit-framework/plugins/aggregator: cannot load such file -- metasploit/aggregator
```

```
# ll | grep aggregator
-rw-r--r--  1 root   root   16977  8월  3 23:14 aggregator.rb
```

Other plugins will load normally.

```
HAHWUL > load wmap

.-.-.-..-.-.-..---..---.
| | | || | | || | || |-'
`-----'`-'-'-'`-^-'`-'
[WMAP 1.5.1] ===  et [  ] metasploit.com 2012
[*] Successfully loaded plugin: wmap

HAHWUL > load msgrpc
[*] MSGRPC Service:  127.0.0.1:55552 
[*] MSGRPC Username: msf
[*] MSGRPC Password: N85ZSU6Y
[*] Successfully loaded plugin: msgrpc
HAHWUL > 
```

Please refer to the execution environment below.

**OS**
OS: Kali2.0 (The same problem occurs in Ubuntu[4.4.0-92-generic])

**Ruby version**
```
# ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
```

**Installation path**
Kali
 + Metasploit: default package
 + Aggregator: gem install (metasploit aggregator)

Ubuntu
 + Metasploit: git clone metasploit framework path
 + Aggregator: gem install (metasploit aggregator)

**Comment by jmartin-r7** [comment]
Note `metasploit-aggregator` is installed gem dependency in `metasploit-framework` so there is not need to gem install it separately as the executor is made available on the path when inside the `metasploit-framework` working directory.

It looks like the Kali build is omitting the aggregator from the `metasploit-framework` specific ruby environment.  I will investigate this further.

On the repository clone, `metasploit-aggregator` gem was just suppressed on master in `metasploit-framework` commit https://github.com/rapid7/metasploit-framework/commit/851c0f4373848838f634aa67c6d7e1d4783e1693 due to another feature that we are working out landing this week.  I expect we will be able to restore the gem shortly.

Please checkout tag 4.15.7 on `metasploit-framework` in the mean time and bundle install there.

**Comment by jmartin-r7** [comment]
Closing, An updated release `1.0.0` has been re-incorporated into `metasploit-framework` as of release `4.16.12`  this should trickle into Kali builds shortly.

**Comment by hahwul** [comment]
Thank you :)
