### ISSUE TITLE
can't load aggregator module

### ISSUE THREAD

**Issue by l0stb1t** [rapid7/metasploit-aggregator#9]
`[-] Failed to load plugin from /usr/share/metasploit-framework/plugins/aggregator: cannot load such file -- metasploit/aggregator
`

**Comment by busterb** [comment]
This looks like a Kali linux specific issue (I'm assuming that's the package you're using, because of the path). You might want to raise an issue on their bug tracker.

**Comment by busterb** [comment]
Yep, Kali linux has removed the aggregator dependency from their package:

http://git.kali.org/gitweb/?p=packages/metasploit-framework.git;a=blob;f=Gemfile;h=9893680a4dd1b27589ee015922be39a5addba7e6;hb=HEAD

It should look like this:
https://github.com/rapid7/metasploit-framework/blob/master/Gemfile#L23

**Comment by busterb** [comment]
Looking at the history, it looks like Kali's fork of Metasploit actually never merged in the required changes in the first place. I wonder why.

http://git.kali.org/gitweb/?p=packages/metasploit-framework.git;a=log
